
service: kinesis-test

package:
  exclude:
    - .env.yml
    - producer.js

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 128
  timeout: 20
  stage: dev
  role: ${file(.env.yml):${opt:stage, self:provider.stage}.lambdaRole}
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/handler1
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/handler2


functions:
  kinesis-test-1:
    handler: handler.kinesisTest
    timeout: 20
    events:
      - stream: 
          arn: ${file(./.env.yml):${opt:stage, self:provider.stage}.eventStream}
          batchSize: 5
          startingPosition: LATEST
          enabled: true
    environment:
      handler_table: handler1
